# Calculater for any operation.



# first_num = float(input("Enter Your 1st num: "))
# operation = input("Chose operation: ")
# second_num = float(input("Enter your 2nd num:"))

# if operation == "+":
#     print("Ans =", first_num + second_num)
# elif(operation == "-"):
#     print("Ans = ", first_num - second_num)
# elif(operation == "*"):
#     print("Ans = ", first_num * second_num)
# elif(operation == "/"):
#     print("Ans = ", first_num / second_num)
# elif(operation == "%"):
#     print("Ans = ", first_num % second_num)
# else:
#     print("invalid syntax")
 
